import Head from 'next/head'
import Link from 'next/link'
import React from 'react'

const Layout = ({ title, children }) => {
    return (
        <>
            <Head>
                <title>{title ? title + '-Ada Derana' : 'Ada Derana'}</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className='flex min-h-screen flex-col justify-between'>
                <header>
                    <nav className='flex h-12 justify-between p-4 shadow-md'>
                        <Link href='/' className='text-lg font-bold'>
                            Ada Drana
                        </Link>
                        <div>
                            <Link href='./Login' className='p-2'>
                                Login
                            </Link>
                        </div>
                    </nav>
                </header>
                <main className='container m-auto mt-6  px-6 lg:px-32  '>
                    {children}
                </main>
                <footer className='flex justify-center h-10 shadow-inner items-center'>Copyright ©2023 Ada Derana. All rights reserved. </footer>
            </div>
        </>
    )
}

export default Layout